### PR TITLE
Unify line endings as LF

### PR DESCRIPTION
**Pull request by ahelwer**
Adds .gitattributes file and converts all files with CRLF line endings to LF following the steps in this guide: https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings

### CODE REVIEW

**Comment by lemmy** [comment]
Should the line endings of the binary files like PNG, PDF, ... really change?

**Comment by ahelwer** [comment]
@lemmy the TLAi linter is failing here for some reason

**Comment by ahelwer** [comment]
@lemmy perhaps not but it's the easiest way to do it, all at once.

**Comment by lemmy** [comment]
> @lemmy the TLAi linter is failing here for some reason

https://github.com/tlaplus/Examples/commit/3d292a837153f1969251d06917ba189f6a916171

**Comment by ahelwer** [comment]
@lemmy seems like the AI workflow is still failing?

**Comment by lemmy** [comment]
> @lemmy seems like the AI workflow is still failing?

Looking into it.  It worked in https://github.com/tlaplus/Examples/pull/127

**Comment by lemmy** [comment]
Appears to be a Github action permission problem.  I suggest to merge this PR ignoring the linter error.

**Pull request merged**
