### PR TITLE
Einstein's Riddle

### PR DESCRIPTION
**Pull request by Isaac-DeFrain**
Solution to Einstein's riddle in the form of a TLA+ spec and TLC model check

There is a README.md and solution.txt which both seem to be ignored

### CODE REVIEW

**Comment by lemmy** [comment]
First of all, there is a bug in the 4. rule, with which this is unsat/there is no solution (a good example of why we should "always be suspicious of success"). The bug is quickly confirmed by making the answer the initial state.  

Secondly, the business of logic puzzles is best solved by @konnov et al. https://github.com/informalsystems/apalache/.  Another way of thinking about this riddle is checking an (inductive) invariant where we don't care about a behavior trace.

```shell
markus@avocado:/tmp/TLAplusFun-main/EinsteinRiddle$ apalache check --config=MC.cfg Einstein
# Tool home: /home/markus/src/TLA/_community/apalache
# Package:   /home/markus/src/TLA/_community/apalache/mod-distribution/target/apalache-pkg-0.11.1-SNAPSHOT-full.jar
# JVM args: -Xmx4096m -DTLA-Library=/home/markus/src/TLA/_community/apalache/src/tla
#
# APALACHE version 0.11.1-SNAPSHOT build v0.11.0-17-gf55663c
#
# WARNING: This tool is in the experimental stage.
#          Please report bugs at: [https://github.com/informalsystems/apalache/issues]
# 
# Usage statistics is ON. Thank you!
# If you have changed your mind, disable the statistics with config --enable-stats=false.

Checker options: filename=Einstein, init=, next=, inv=            I@16:42:13.213
Tuning:                                                           I@16:42:13.644
PASS #0: SanyParser                                               I@16:42:13.645
Parsing file /tmp/TLAplusFun-main/EinsteinRiddle/Einstein.tla
Parsing file /tmp/Naturals.tla
Parsing file /tmp/FiniteSets.tla
Parsing file /tmp/Sequences.tla
PASS #1: ConfigurationPass                                        I@16:42:14.291
  > MC.cfg: Loading TLC configuration                             I@16:42:14.294
  > MC.cfg: Using SPECIFICATION Spec                              I@16:42:14.410
  > Using the init predicate Init from the TLC config             I@16:42:14.411
  > Using the next predicate Next from the TLC config             I@16:42:14.411
  > MC.cfg: found INVARIANTS: FindSolution                        I@16:42:14.411
  > Set the initialization predicate to Init                      I@16:42:14.412
  > Set the transition predicate to Next                          I@16:42:14.413
  > Set an invariant to FindSolution                              I@16:42:14.413
  > Replaced CONSTANT PETS with {"bird", "cat", "dog", "fish", "horse"} I@16:42:14.416
  > Replaced CONSTANT CIGARS with {"blend", "bm", "dh", "pm", "prince"} I@16:42:14.416
  > Replaced CONSTANT NATIONALITIES with {"brit", "swede", "dane", "norwegian", "german"} I@16:42:14.417
  > Replaced CONSTANT COLORS with {"red", "white", "blue", "green", "yellow"} I@16:42:14.417
  > Replaced CONSTANT DRINKS with {"beer", "coffee", "mylk", "tea", "water"} I@16:42:14.417
PASS #2: DesugarerPass                                            I@16:42:14.497
  > Desugaring...                                                 I@16:42:14.498
PASS #3: UnrollPass                                               I@16:42:14.545
  > Unroller                                                      I@16:42:14.596
PASS #4: PrimingPass                                              I@16:42:14.628
  > Introducing InitPrimed for Init'                              I@16:42:14.635
PASS #5: CoverAnalysisPass                                        I@16:42:14.691
PASS #6: InlinePass                                               I@16:42:14.692
  > InlinerOfUserOper                                             I@16:42:14.702
  > LetInExpander                                                 I@16:42:14.722
  > InlinerOfUserOper                                             I@16:42:14.730
Leaving only relevant operators: CInitPrimed, FindSolution, Init, InitPrimed, Next I@16:42:14.738
PASS #7: VCGen                                                    I@16:42:14.781
  > Producing verification conditions from the invariant FindSolution I@16:42:14.782
  > VCGen produced 1 verification condition(s)                    I@16:42:14.783
PASS #8: PreprocessingPass                                        I@16:42:14.833
  > Before preprocessing: unique renaming                         I@16:42:14.834
 > Applying standard transformations:                             I@16:42:14.842
  > PrimePropagation                                              I@16:42:14.842
  > Desugarer                                                     I@16:42:14.895
  > UniqueRenamer                                                 I@16:42:14.945
  > Normalizer                                                    I@16:42:15.017
  > Keramelizer                                                   I@16:42:15.084
  > After preprocessing: UniqueRenamer                            I@16:42:15.171
PASS #9: TransitionFinderPass                                     I@16:42:15.233
  > Found 1 initializing transitions                              I@16:42:15.288
  > Found 1 transitions                                           I@16:42:15.298
  > No constant initializer                                       I@16:42:15.298
  > Applying unique renaming                                      I@16:42:15.299
PASS #10: OptimizationPass                                        I@16:42:15.348
 > Applying optimizations:                                        I@16:42:15.356
  > ConstSimplifier                                               I@16:42:15.357
  > ExprOptimizer                                                 I@16:42:15.377
  > ConstSimplifier                                               I@16:42:15.386
PASS #11: AnalysisPass                                            I@16:42:15.423
 > Marking skolemizable existentials and sets to be expanded...   I@16:42:15.426
  > SkolemizationMarker                                           I@16:42:15.427
  > ExpansionMarker                                               I@16:42:15.429
 > Running analyzers...                                           I@16:42:15.444
  > Introduced expression grades                                  I@16:42:15.486
  > Introduced 3 formula hints                                    I@16:42:15.486
PASS #12: BoundedChecker                                          I@16:42:15.486
State 0: Checking 1 invariants                                    I@16:42:16.685
State 0: Invariant 0 violated. Check the counterexample in: counterexample.tla, MC.out, counterexample.json E@16:42:16.909
The outcome is: Error                                             I@16:42:16.914
Checker has found an error                                        I@16:42:16.914
It took me 0 days  0 hours  0 min  3 sec                          I@16:42:16.916
Total time: 3.703 sec                                             I@16:42:16.917
EXITCODE: OK

markus@avocado:/tmp/TLAplusFun-main/EinsteinRiddle$ cat MC.out 
@!@!@STARTMSG 2262:0 @!@!@
Created by Apalache on Wed Mar 10 16:42:16 PST 2021
@!@!@ENDMSG 2262 @!@!@
@!@!@STARTMSG 2110:1 @!@!@
Invariant is violated.
@!@!@ENDMSG 2110 @!@!@
@!@!@STARTMSG 2121:1 @!@!@
The behavior up to this point is:
@!@!@ENDMSG 2121 @!@!@
@!@!@STARTMSG 2217:4 @!@!@
1: <Initial predicate>
/\ cigars = 1 :> "dh" @@ 2 :> "blend" @@ 3 :> "pm" @@ 4 :> "prince" @@ 5 :> "bm"
/\ colors = 1 :> "yellow" @@ 2 :> "blue" @@ 3 :> "red" @@ 4 :> "green" @@ 5 :> "white"
/\ drinks = 1 :> "water" @@ 2 :> "tea" @@ 3 :> "mylk" @@ 4 :> "coffee" @@ 5 :> "beer"
/\ nationality = 1 :> "norwegian" @@ 2 :> "dane" @@ 3 :> "brit" @@ 4 :> "german" @@ 5 :> "swede"
/\ pets = 1 :> "cat" @@ 2 :> "horse" @@ 3 :> "bird" @@ 4 :> "fish" @@ 5 :> "dog"
@!@!@ENDMSG 2217 @!@!@
```


4 seconds; impossible to beat with TLC!!!  With regards to TLC, there are two observations:

1) Permutation(..) is evaluated for *every* state (the Toolbox's profiler would have reported this)
2) TLC generates initial states sequentially and, thus, does *not* benefit from more than one worker

To address 1) and because another set of constants makes no sense for this riddle anyway, one could replace the CONSTANTS with:

```tla
Permutation(S) == 
    { p \in [ 1..5 -> S ] :
        /\ p[2] \in S \ {p[1]}
        /\ p[3] \in S \ {p[1], p[2]}
        /\ p[4] \in S \ {p[1], p[2], p[3]}
        /\ p[5] \in S \ {p[1], p[2], p[3], p[4]} }

NATIONALITIES == Permutation({ "brit", "swede", "dane", "norwegian", "german" })
DRINKS == Permutation({ "beer", "coffee", "mylk", "tea", "water" })
COLORS == Permutation({ "red", "white", "blue", "green", "yellow" })
PETS == Permutation({ "bird", "cat", "dog", "fish", "horse" })
CIGARS == Permutation({ "blend", "bm", "dh", "pm", "prince" })
```

For 2), choosing one of the type-correct states in `Init` and changing the old `Init` into `Next` would do the trick:

```tla
Init ==
    /\ drinks = CHOOSE d \in DRINKS : d[3] = "mylk"
    /\ nationality = CHOOSE n \in NATIONALITIES : n[1] = "norwegian"
    /\ colors = CHOOSE c \in COLORS: TRUE
    /\ pets = CHOOSE p \in PETS: TRUE
    /\ cigars = CHOOSE c \in CIGARS: TRUE

Next ==
    /\ drinks' \in { p \in DRINKS : p[3] = "mylk" }
    /\ nationality' \in { p \in NATIONALITIES : p[1] = "norwegian" }
    /\ colors' \in COLORS
    /\ pets' \in PETS
    /\ cigars' \in CIGARS
```

However, since Apalache is clearly the tool of choice here and because it no longer accepts this spec variant (see below), it is best to keep the (corrected) spec and add a comment that points at Apalache.  Also, the actual question "Who owns the fish?" should be included in the prose description of the riddle.

```
markus@avocado:~/src/TLA/_specs/examples/specifications/EinsteinRiddle(Isaac-DeFrain-master)$ apalache check --config=Einstein.cfg Einstein
# Tool home: /home/markus/src/TLA/_community/apalache
# Package:   /home/markus/src/TLA/_community/apalache/mod-distribution/target/apalache-pkg-0.11.1-SNAPSHOT-full.jar
# JVM args: -Xmx4096m -DTLA-Library=/home/markus/src/TLA/_community/apalache/src/tla
#
# APALACHE version 0.11.1-SNAPSHOT build v0.11.0-17-gf55663c
#
# WARNING: This tool is in the experimental stage.
#          Please report bugs at: [https://github.com/informalsystems/apalache/issues]
# 
# Usage statistics is ON. Thank you!
# If you have changed your mind, disable the statistics with config --enable-stats=false.

Checker options: filename=Einstein, init=, next=, inv=            I@17:26:44.604
Tuning:                                                           I@17:26:45.545
PASS #0: SanyParser                                               I@17:26:45.547
Parsing file /home/markus/src/TLA/_specs/examples/specifications/EinsteinRiddle/Einstein.tla
Parsing file /tmp/Naturals.tla
Parsing file /tmp/FiniteSets.tla
Parsing file /tmp/Sequences.tla
PASS #1: ConfigurationPass                                        I@17:26:46.825
  > Einstein.cfg: Loading TLC configuration                       I@17:26:46.828
  > Einstein.cfg: Using SPECIFICATION Spec                        I@17:26:46.987
  > Using the init predicate Init from the TLC config             I@17:26:46.989
  > Using the next predicate Next from the TLC config             I@17:26:46.991
  > Einstein.cfg: found INVARIANTS: FindSolution                  I@17:26:46.993
  > Set the initialization predicate to Init                      I@17:26:46.997
  > Set the transition predicate to Next                          I@17:26:47.005
  > Set an invariant to FindSolution                              I@17:26:47.012
PASS #2: DesugarerPass                                            I@17:26:47.149
  > Desugaring...                                                 I@17:26:47.159
PASS #3: UnrollPass                                               I@17:26:47.220
  > Unroller                                                      I@17:26:47.348
PASS #4: PrimingPass                                              I@17:26:47.413
  > Introducing InitPrimed for Init'                              I@17:26:47.424
PASS #5: CoverAnalysisPass                                        I@17:26:47.534
PASS #6: InlinePass                                               I@17:26:47.538
  > InlinerOfUserOper                                             I@17:26:47.556
  > LetInExpander                                                 I@17:26:47.620
  > InlinerOfUserOper                                             I@17:26:47.641
Leaving only relevant operators: CInitPrimed, FindSolution, Init, InitPrimed, Next I@17:26:47.662
PASS #7: VCGen                                                    I@17:26:47.802
  > Producing verification conditions from the invariant FindSolution I@17:26:47.804
  > VCGen produced 1 verification condition(s)                    I@17:26:47.809
PASS #8: PreprocessingPass                                        I@17:26:47.923
  > Before preprocessing: unique renaming                         I@17:26:47.934
 > Applying standard transformations:                             I@17:26:47.952
  > PrimePropagation                                              I@17:26:47.956
  > Desugarer                                                     I@17:26:48.058
  > UniqueRenamer                                                 I@17:26:48.175
  > Normalizer                                                    I@17:26:48.340
  > Keramelizer                                                   I@17:26:48.478
  > After preprocessing: UniqueRenamer                            I@17:26:48.659
PASS #9: TransitionFinderPass                                     I@17:26:48.826
  > Found 1 initializing transitions                              I@17:26:48.914
  > Found 1 transitions                                           I@17:26:48.959
  > No constant initializer                                       I@17:26:48.961
  > Applying unique renaming                                      I@17:26:48.968
PASS #10: OptimizationPass                                        I@17:26:49.063
 > Applying optimizations:                                        I@17:26:49.071
  > ConstSimplifier                                               I@17:26:49.078
  > ExprOptimizer                                                 I@17:26:49.112
  > ConstSimplifier                                               I@17:26:49.162
PASS #11: AnalysisPass                                            I@17:26:49.265
 > Marking skolemizable existentials and sets to be expanded...   I@17:26:49.269
  > SkolemizationMarker                                           I@17:26:49.271
  > ExpansionMarker                                               I@17:26:49.275
The set [(1 .. 5) → {"beer", "coffee", "mylk", "tea", "water"}] will be expanded. This will blow up the solver. W@17:26:49.285
The set [(1 .. 5) → {"brit", "swede", "dane", "norwegian", "german"}] will be expanded. This will blow up the solver. W@17:26:49.291
The set [(1 .. 5) → {"red", "white", "blue", "green", "yellow"}] will be expanded. This will blow up the solver. W@17:26:49.302
The set [(1 .. 5) → {"bird", "cat", "dog", "fish", "horse"}] will be expanded. This will blow up the solver. W@17:26:49.306
The set [(1 .. 5) → {"blend", "bm", "dh", "pm", "prince"}] will be expanded. This will blow up the solver. W@17:26:49.309
The set [(1 .. 5) → {"beer", "coffee", "mylk", "tea", "water"}] will be expanded. This will blow up the solver. W@17:26:49.318
The set [(1 .. 5) → {"brit", "swede", "dane", "norwegian", "german"}] will be expanded. This will blow up the solver. W@17:26:49.322
The set [(1 .. 5) → {"red", "white", "blue", "green", "yellow"}] will be expanded. This will blow up the solver. W@17:26:49.325
The set [(1 .. 5) → {"bird", "cat", "dog", "fish", "horse"}] will be expanded. This will blow up the solver. W@17:26:49.332
The set [(1 .. 5) → {"blend", "bm", "dh", "pm", "prince"}] will be expanded. This will blow up the solver. W@17:26:49.336
 > Running analyzers...                                           I@17:26:49.347
  > Introduced expression grades                                  I@17:26:49.441
  > Introduced 3 formula hints                                    I@17:26:49.445
PASS #12: BoundedChecker                                          I@17:26:49.447
(Please report an issue at: [https://github.com/informalsystems/apalache/issues],at.forsyte.apalache.tla.bmcmt.RewriterException: Trying to expand a set of functions. This will blow up the solver.)
Einstein.tla:43:13-43:25: rewriter error: Trying to expand a set of functions. This will blow up the solver. E@17:26:50.050
at.forsyte.apalache.tla.bmcmt.RewriterException: Trying to expand a set of functions. This will blow up the solver.
	at at.forsyte.apalache.tla.bmcmt.rules.SetExpandRule.apply(SetExpandRule.scala:26)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteOnce(SymbStateRewriterImpl.scala:334)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.doRecursive$1(SymbStateRewriterImpl.scala:365)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteUntilDone(SymbStateRewriterImpl.scala:396)
	at at.forsyte.apalache.tla.bmcmt.rules.SetFilterRule.apply(SetFilterRule.scala:26)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteOnce(SymbStateRewriterImpl.scala:334)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.doRecursive$1(SymbStateRewriterImpl.scala:365)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteUntilDone(SymbStateRewriterImpl.scala:396)
	at at.forsyte.apalache.tla.bmcmt.rules.SetFilterRule.apply(SetFilterRule.scala:26)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteOnce(SymbStateRewriterImpl.scala:334)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.doRecursive$1(SymbStateRewriterImpl.scala:365)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteUntilDone(SymbStateRewriterImpl.scala:396)
	at at.forsyte.apalache.tla.bmcmt.rules.ChooseRule.apply(ChooseRule.scala:40)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteOnce(SymbStateRewriterImpl.scala:334)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.doRecursive$1(SymbStateRewriterImpl.scala:365)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteUntilDone(SymbStateRewriterImpl.scala:396)
	at at.forsyte.apalache.tla.bmcmt.rules.AssignmentRule.apply(AssignmentRule.scala:39)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteOnce(SymbStateRewriterImpl.scala:334)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.doRecursive$1(SymbStateRewriterImpl.scala:365)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteUntilDone(SymbStateRewriterImpl.scala:396)
	at at.forsyte.apalache.tla.bmcmt.rules.AndRule.mapArg$1(AndRule.scala:74)
	at at.forsyte.apalache.tla.bmcmt.rules.AndRule.$anonfun$apply$2(AndRule.scala:78)
	at scala.collection.immutable.List.map(List.scala:293)
	at at.forsyte.apalache.tla.bmcmt.rules.AndRule.apply(AndRule.scala:78)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteOnce(SymbStateRewriterImpl.scala:334)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.doRecursive$1(SymbStateRewriterImpl.scala:365)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteUntilDone(SymbStateRewriterImpl.scala:396)
	at at.forsyte.apalache.tla.bmcmt.trex.TransitionExecutorImpl.prepareTransition(TransitionExecutorImpl.scala:102)
	at at.forsyte.apalache.tla.bmcmt.trex.FilteredTransitionExecutor.prepareTransition(FilteredTransitionExecutor.scala:34)
	at at.forsyte.apalache.tla.bmcmt.SeqModelChecker.$anonfun$prepareTransitionsAndCheckInvariants$5(SeqModelChecker.scala:112)
	at at.forsyte.apalache.tla.bmcmt.SeqModelChecker.$anonfun$prepareTransitionsAndCheckInvariants$5$adapted(SeqModelChecker.scala:106)
	at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:924)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:923)
	at at.forsyte.apalache.tla.bmcmt.SeqModelChecker.prepareTransitionsAndCheckInvariants(SeqModelChecker.scala:106)
	at at.forsyte.apalache.tla.bmcmt.SeqModelChecker.makeStep(SeqModelChecker.scala:51)
	at at.forsyte.apalache.tla.bmcmt.SeqModelChecker.run(SeqModelChecker.scala:31)
	at at.forsyte.apalache.tla.bmcmt.passes.BoundedCheckerPassImpl.runIncrementalChecker(BoundedCheckerPassImpl.scala:122)
	at at.forsyte.apalache.tla.bmcmt.passes.BoundedCheckerPassImpl.execute(BoundedCheckerPassImpl.scala:88)
	at at.forsyte.apalache.infra.passes.PassChainExecutor.exec$1(PassChainExecutor.scala:22)
	at at.forsyte.apalache.infra.passes.PassChainExecutor.run(PassChainExecutor.scala:37)
	at at.forsyte.apalache.tla.Tool$.runCheck(Tool.scala:173)
	at at.forsyte.apalache.tla.Tool$.$anonfun$run$2(Tool.scala:95)
	at at.forsyte.apalache.tla.Tool$.$anonfun$run$2$adapted(Tool.scala:95)
	at at.forsyte.apalache.tla.Tool$.handleExceptions(Tool.scala:258)
	at at.forsyte.apalache.tla.Tool$.run(Tool.scala:95)
	at at.forsyte.apalache.tla.Tool$.main(Tool.scala:45)
	at at.forsyte.apalache.tla.Tool.main(Tool.scala)
It took me 0 days  0 hours  0 min  5 sec                          I@17:26:50.056
Total time: 5.460 sec                                             I@17:26:50.058
EXITCODE: ERROR (99)
```

**Comment by Isaac-DeFrain** [comment]
Wow that was an egregious oversight on my part... that’s an old (clearly incorrect) spec that spoiled my PR. My apologies for that.

Great idea using Apalache! That’s impressive that it took less than 4 seconds.

Thanks for the suggestions, I’ll make some changes and update.

**Comment by lemmy** [comment]
As a quick check with TLAPS:

```tla
Answer ==
    /\ drinks = <<"water", "tea", "mylk", "coffee", "beer">>
    /\ nationality = <<"norwegian", "dane", "brit", "german", "swede">>
    /\ colors = <<"yellow", "blue", "red", "green", "white">>
    /\ pets = <<"cat", "horse", "bird", "fish", "dog">>
    /\ cigars = <<"dh", "blend", "pm", "prince", "bm">>

THEOREM InitConstraints /\ Solution <=> Answer 
BY DEF InitConstraints, Solution, Answer,
           BritLivesInTheRedHouse, SwedeKeepsDogs, DaneDrinksTea, 
           GreenLeftOfWhite,
           GreenOwnerDrinksCoffee, SmokesPallmallRearsBirds, YellowOwnerSmokesDunhill, 
           CenterDrinksMylk, NorwegianFirstHouse, BlendSmokerLivesNextToCatOwner, 
           HorseKeeperLivesNextToDunhillSmoker, BluemasterSmokerDrinksBeer, GermanSmokesPrince, 
           NorwegianLivesNextToBlueHouse, BlendSmokerHasWaterDrinkingNeighbor,
           DRINKS, NATIONALITIES, COLORS, PETS, CIGARS, 
           Permutation
```

**Comment by konnov** [comment]
Cool that it works fast with Apalache. It rightfully complains that combinatorial explosion is to be expected. As for the stack trace, we have to wrap such error messages with nice explanations. Planned in https://github.com/informalsystems/apalache/issues/548

**Comment by konnov** [comment]
> First of all, there is a bug in the 4. rule, with which this is unsat/there is no solution (a good example of why we should "always be suspicious of success"). The bug is quickly confirmed by making the answer the initial state.

For some time, I had a suspicion that we have to provide per-operator checks. We are planning to investigate that with:
https://github.com/informalsystems/apalache/issues/622

**Comment by lemmy** [comment]
In this case, it would be nice if TLAPS would automatically complain about `GreenLeftOfWhite`.

**Comment by Isaac-DeFrain** [comment]
@lemmy I fixed the error in rule 4 and included other simplifications. Would you like me to make any other changes?

**Comment by lemmy** [comment]
Cherry-picked with https://github.com/tlaplus/Examples/commit/6aef336d97d7a18039692283236d532fcb6a6483 and refactored in https://github.com/tlaplus/Examples/commit/a9c08fd68e4e646855ca9fb5e49db4804ffc07d4.

**Comment by lemmy** [comment]
FWIW: https://github.com/tlaplus/Examples/commit/22e6b2daae5e0173ac856e8eab5c01abd90b39d4#diff-7829468e86c1cc5d5133195b5cb48e1ff6c75e3e9203777f6b2e379d9e4882b3R40-R43

**Pull request closed without merging**
