### PR TITLE
Added TLC models for all viable specs

### LINKED ISSUE #107: Add TLC models for all specs for which it's viable
The README table validation work reveals that a bit more than half the specs in this repo have a TLC model associated with them. Adding TLC models to the remainder (if viable) would be an easy way to have improved confidence that the specs in this repo are actually correct (in the sense of capable of being validated, not exhibiting simple type errors, etc.) and would expand the functional test suite for the TLA+ tools.

### PR DESCRIPTION
**Pull request by ahelwer**
WIP
Models added for:
 - TeachingConcurrency
 - Stones
 - Bakery-Boulangerie (ref #109)
 - LoopInvariance
 - bcastByz
 - sums_even
 - TwoPhase
 - lamport_mutex
 - Paxos (How to Win a Turing Award)
 - Chang-Roberts
 - Aynchronous Byzantine Consensus
 - Folklore Reliable Broadcast
 - Bosco Consensus
 - Consensus in 1 Communication Step
 - One-Step Consensus with Zero Degradation
 - Failure Detector
 - Bunch of others

Closes #107

### CODE REVIEW

**Comment by lemmy** [comment]
Doesn't the last commit make it impossible for Toolbox users to import the models?  According to our community survey, about half of our users use the Toolbox.

**Comment by ahelwer** [comment]
What files do the toolbox users need to import a model? I had added the missing modules in the toolbox model style in a previous commit, but all the duplicated modules were messing with the lists of modules to skip proof testing on.

**Comment by lemmy** [comment]
The `3Values` model for a `Consensus` spec would need the following three files: 

`Consensus.toolbox/.project`
`Consensus.toolbox/.settings/org.lamport.tla.toolbox.prefs`
`Consensus.toolbox/Consensus___3Values.launch`

**Comment by ahelwer** [comment]
So the copied .tla files and MC.tla/.cfg files don't need to be present?

**Comment by lemmy** [comment]
IIRC, the Toolbox will copy them from the spec's root folder.

**Pull request merged**
