### PR TITLE
Add multiple specs with models

### PR DESCRIPTION
**Pull request by ahelwer**
- Coffee can math problem
- Multi-car elevator system
- Key-value store with snapshot isolation
- Nano blockchain
- Slush probabilistic consensus protocol

### CODE REVIEW

**Comment by lemmy** [comment]
Looks good to me.  The KVS spec could use more comments.

**Comment by ahelwer** [comment]
@lemmy added a header comment in the KVS spec. Is this signoff/DCO thing a feature you enabled on this repo? Learning about it for the first time.

**Comment by lemmy** [comment]
> @lemmy added a header comment in the KVS spec. Is this signoff/DCO thing a feature you enabled on this repo? Learning about it for the first time.

DCO was recommended by the folks from the Linux Foundation as part of the onboarding process.  Problems with it?

**Comment by ahelwer** [comment]
I'm trying to avoid spam so I use my mozmail relay for commits on here.

**Comment by lemmy** [comment]
Merged, but something is wrong with the rendering of README.md.

**Comment by ahelwer** [comment]
Oh, hmm. Looks like the links aren't displaying. Slush should also be marked as a pluscal spec. Will fix in a few hours.

**Pull request merged**
