### PR TITLE
Use macOS runner, minor script debug output fixes

### PR DESCRIPTION
**Pull request by ahelwer**
Print out TLC command line call in smoke testing script and decode TLC output as UTF-8 if necessary.
Ref #119

### CODE REVIEW

**Comment by lemmy** [comment]
What does the minor script fix do?

**Comment by ahelwer** [comment]
Sometimes (varies depending on OS and also way in which the process terminated) stdout is given in bytes, and sometimes it's given as a string. So this just ensures it's always printed out as a string in the smoke testing script.

**Comment by lemmy** [comment]
I'd suggest to make that the git commit message for that particular change.

**Comment by ahelwer** [comment]
Sure, I will put that in the squash commit message.

**Pull request merged**
