### PR TITLE
Specifying and Verifying SDP Protocol based Zero Trust Architecture

### PR DESCRIPTION
**Pull request by 10227694**
I have modified this project according to  Stephan's comments.
Now I believe  the spec is qualified to be merged to the collection. Please check, Thanks a lot.

### CODE REVIEW

**Comment by lemmy** [comment]
@10227694 We haven't gotten around to reviewing this PR.  Why did you closed it?

**Comment by 10227694** [comment]
Sorry，wrong operation to close it due to my carelessness, I'd repoen it for check.

**Comment by niuzhi** [comment]
@lemmy Hello, is this PR review over?
https://github.com/tlaplus/Examples/issues/56

**Comment by lemmy** [comment]
I haven't had a chance to look at this PR, but I believe @muenchnerkindl has.

**Comment by muenchnerkindl** [comment]
Thank you very much for your contribution. I'll be happy to merge the pull request.

In the process of setting up the TLA+ Foundation and following the general rules of the Linux Foundation, we now require all commits to include a DCO signoff. Please follow the instructions at https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md and include a DCO: without this, I cannot merge your contribution.

Thanks,
Stephan

**Comment by 10227694** [comment]
> Thank you very much for your contribution. I'll be happy to merge the pull request.
> 
> In the process of setting up the TLA+ Foundation and following the general rules of the Linux Foundation, we now require all commits to include a DCO signoff. Please follow the instructions at https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md and include a DCO: without this, I cannot merge your contribution.
> 
> Thanks, Stephan

thanks.The DCO problem has been repaired as required, and the latest PR list is
https://github.com/tlaplus/Examples/pull/62

**Pull request closed without merging**
